#!/bin/bash
#
# Git Mirror Setup for Tailnet Peers
#
# This script sets up bidirectional Git mirroring between two machines.
# Each machine maintains mirrors of the other's repositories.
# Run this script on BOTH machines with appropriate configuration.
#
# Usage:
#   1. Edit the CONFIGURATION section below
#   2. Run: ./git-mirror-setup.sh setup
#   3. Add repos to mirror: ./git-mirror-setup.sh add-mirror <remote-repo-path>
#   4. Sync now: ./git-mirror-setup.sh sync
#

set -euo pipefail

# ============================================================================
# CONFIGURATION - Edit these for your machine
# ============================================================================

# Your local git repositories directory (bare repos you want to share)
LOCAL_GIT_DIR="$HOME/git"

# Where to store mirrors of the remote machine's repos
LOCAL_MIRROR_DIR="$HOME/mirrors"

# Remote machine's Tailnet hostname (e.g., "pauls-macmini" or "afcs-macmini")
REMOTE_HOST="CHANGEME"

# Your username on the remote machine
REMOTE_USER="CHANGEME"

# Remote machine's git directory (where their repos live)
REMOTE_GIT_DIR="/Users/${REMOTE_USER}/git"

# How often to sync (cron schedule)
# Every 4 hours: "0 */4 * * *"
# Every hour:    "0 * * * *"
# Daily at 2am:  "0 2 * * *"
CRON_SCHEDULE="0 */4 * * *"

# Log file for sync operations
LOG_FILE="$HOME/.git-mirror-sync.log"

# ============================================================================
# MATTERMOST NOTIFICATIONS (optional)
# ============================================================================

# Mattermost incoming webhook URL
# Create one at: Your Mattermost > Integrations > Incoming Webhooks
# Leave empty to disable notifications
MATTERMOST_WEBHOOK_URL=""

# Channel to post to (optional - webhook has a default channel)
# Use channel name like "town-square" or leave empty for webhook default
MATTERMOST_CHANNEL=""

# Only notify on failures (true) or all syncs (false)
MATTERMOST_FAILURES_ONLY="true"

# ============================================================================
# END CONFIGURATION
# ============================================================================

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SYNC_SCRIPT="$HOME/.local/bin/git-mirror-sync.sh"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"
}

check_config() {
    if [[ "$REMOTE_HOST" == "CHANGEME" ]] || [[ "$REMOTE_USER" == "CHANGEME" ]]; then
        echo "ERROR: Please edit this script and set REMOTE_HOST and REMOTE_USER"
        exit 1
    fi
}

cmd_setup() {
    check_config
    log "Setting up Git mirror infrastructure..."

    # Create directories
    log "Creating directories..."
    mkdir -p "$LOCAL_GIT_DIR"
    mkdir -p "$LOCAL_MIRROR_DIR/$REMOTE_HOST"
    mkdir -p "$HOME/.local/bin"

    # Check SSH connectivity
    log "Testing SSH connectivity to $REMOTE_HOST..."
    if ! ssh -o ConnectTimeout=5 "$REMOTE_HOST" "echo 'SSH connection successful'" 2>/dev/null; then
        echo ""
        echo "SSH connection failed. Let's set up SSH keys."
        echo ""
        setup_ssh_keys
    else
        log "SSH connection working."
    fi

    # Create the sync script
    log "Creating sync script at $SYNC_SCRIPT..."
    create_sync_script

    # Set up cron
    log "Setting up cron job..."
    setup_cron

    echo ""
    log "Setup complete!"
    echo ""
    echo "Next steps:"
    echo "  1. Add repos to mirror:  $0 add-mirror /path/on/remote/repo.git"
    echo "  2. List mirrored repos:  $0 list"
    echo "  3. Sync now:             $0 sync"
    echo "  4. View logs:            tail -f $LOG_FILE"
    echo ""
}

setup_ssh_keys() {
    local key_file="$HOME/.ssh/id_ed25519"

    # Generate key if needed
    if [[ ! -f "$key_file" ]]; then
        log "Generating SSH key..."
        ssh-keygen -t ed25519 -C "$(whoami)@$(hostname)" -f "$key_file" -N ""
    fi

    echo ""
    echo "To set up passwordless SSH, run this command:"
    echo ""
    echo "  ssh-copy-id $REMOTE_USER@$REMOTE_HOST"
    echo ""
    echo "Then re-run: $0 setup"
    echo ""
}

create_sync_script() {
    cat > "$SYNC_SCRIPT" << 'SYNCSCRIPT'
#!/bin/bash
#
# Git Mirror Sync Script
# Generated by git-mirror-setup.sh
#

set -euo pipefail

# Configuration (injected at generation time)
REMOTE_HOST="__REMOTE_HOST__"
REMOTE_USER="__REMOTE_USER__"
REMOTE_GIT_DIR="__REMOTE_GIT_DIR__"
LOCAL_MIRROR_DIR="__LOCAL_MIRROR_DIR__"
LOG_FILE="__LOG_FILE__"
MATTERMOST_WEBHOOK_URL="__MATTERMOST_WEBHOOK_URL__"
MATTERMOST_CHANNEL="__MATTERMOST_CHANNEL__"
MATTERMOST_FAILURES_ONLY="__MATTERMOST_FAILURES_ONLY__"

LOCAL_HOSTNAME="$(hostname -s)"
FAILED_REPOS=()
SYNCED_REPOS=()

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"
}

# Send notification to Mattermost
notify_mattermost() {
    local status="$1"
    local message="$2"

    # Skip if webhook not configured
    [[ -z "$MATTERMOST_WEBHOOK_URL" ]] && return 0

    # Skip success notifications if failures_only is set
    if [[ "$MATTERMOST_FAILURES_ONLY" == "true" ]] && [[ "$status" == "success" ]]; then
        return 0
    fi

    local icon=":white_check_mark:"
    local color="#36a64f"
    if [[ "$status" == "failure" ]]; then
        icon=":x:"
        color="#dc3545"
    elif [[ "$status" == "warning" ]]; then
        icon=":warning:"
        color="#ffc107"
    fi

    local payload
    payload=$(cat <<EOF
{
    "username": "Git Mirror",
    "icon_emoji": ":git:",
    "attachments": [{
        "color": "$color",
        "title": "$icon Git Mirror Sync - $LOCAL_HOSTNAME",
        "text": "$message",
        "footer": "git-mirror-sync | $(date '+%Y-%m-%d %H:%M:%S')"
    }]
}
EOF
)

    # Add channel override if specified
    if [[ -n "$MATTERMOST_CHANNEL" ]]; then
        payload=$(echo "$payload" | jq --arg ch "$MATTERMOST_CHANNEL" '. + {channel: $ch}')
    fi

    curl -s -X POST \
        -H "Content-Type: application/json" \
        -d "$payload" \
        "$MATTERMOST_WEBHOOK_URL" >/dev/null 2>&1 || log "Warning: Failed to send Mattermost notification"
}

# Check if remote is reachable
if ! ssh -o ConnectTimeout=10 "$REMOTE_HOST" "true" 2>/dev/null; then
    log "ERROR: Cannot reach $REMOTE_HOST - skipping sync"
    notify_mattermost "failure" "Cannot reach **$REMOTE_HOST** - sync aborted"
    exit 1
fi

log "Starting sync from $REMOTE_HOST..."

# Sync each mirrored repo
MIRROR_DIR="$LOCAL_MIRROR_DIR/$REMOTE_HOST"
if [[ -d "$MIRROR_DIR" ]]; then
    for repo in "$MIRROR_DIR"/*.git; do
        if [[ -d "$repo" ]]; then
            repo_name=$(basename "$repo")
            log "Syncing $repo_name..."
            if git -C "$repo" remote update --prune 2>&1 | tee -a "$LOG_FILE"; then
                log "  $repo_name: OK"
                SYNCED_REPOS+=("$repo_name")
            else
                log "  $repo_name: FAILED"
                FAILED_REPOS+=("$repo_name")
            fi
        fi
    done
else
    log "No mirrors configured yet. Use 'git-mirror-setup.sh add-mirror' to add repos."
fi

log "Sync complete."

# Send summary notification
if [[ ${#FAILED_REPOS[@]} -gt 0 ]]; then
    failed_list=$(printf "• %s\n" "${FAILED_REPOS[@]}")
    notify_mattermost "failure" "Sync from **$REMOTE_HOST** completed with errors:\n\n**Failed repos:**\n$failed_list\n\n**Successful:** ${#SYNCED_REPOS[@]} repos"
elif [[ ${#SYNCED_REPOS[@]} -gt 0 ]]; then
    notify_mattermost "success" "Sync from **$REMOTE_HOST** completed successfully: ${#SYNCED_REPOS[@]} repos updated"
fi
SYNCSCRIPT

    # Inject configuration
    sed -i '' "s|__REMOTE_HOST__|$REMOTE_HOST|g" "$SYNC_SCRIPT"
    sed -i '' "s|__REMOTE_USER__|$REMOTE_USER|g" "$SYNC_SCRIPT"
    sed -i '' "s|__REMOTE_GIT_DIR__|$REMOTE_GIT_DIR|g" "$SYNC_SCRIPT"
    sed -i '' "s|__LOCAL_MIRROR_DIR__|$LOCAL_MIRROR_DIR|g" "$SYNC_SCRIPT"
    sed -i '' "s|__LOG_FILE__|$LOG_FILE|g" "$SYNC_SCRIPT"
    sed -i '' "s|__MATTERMOST_WEBHOOK_URL__|$MATTERMOST_WEBHOOK_URL|g" "$SYNC_SCRIPT"
    sed -i '' "s|__MATTERMOST_CHANNEL__|$MATTERMOST_CHANNEL|g" "$SYNC_SCRIPT"
    sed -i '' "s|__MATTERMOST_FAILURES_ONLY__|$MATTERMOST_FAILURES_ONLY|g" "$SYNC_SCRIPT"

    chmod +x "$SYNC_SCRIPT"
}

setup_cron() {
    local cron_line="$CRON_SCHEDULE $SYNC_SCRIPT"
    local cron_marker="# git-mirror-sync"

    # Remove old entry if exists, add new one
    (crontab -l 2>/dev/null | grep -v "$cron_marker" || true; echo "$cron_line $cron_marker") | crontab -

    log "Cron job installed: $CRON_SCHEDULE"
}

cmd_add_mirror() {
    check_config
    local remote_repo_path="${1:-}"

    if [[ -z "$remote_repo_path" ]]; then
        echo "Usage: $0 add-mirror <remote-repo-path>"
        echo ""
        echo "Examples:"
        echo "  $0 add-mirror /Users/paul/git/myproject.git"
        echo "  $0 add-mirror ~/git/myproject.git"
        echo ""
        echo "To see what repos are available on $REMOTE_HOST:"
        echo "  $0 list-remote"
        exit 1
    fi

    local repo_name=$(basename "$remote_repo_path")
    local local_path="$LOCAL_MIRROR_DIR/$REMOTE_HOST/$repo_name"

    if [[ -d "$local_path" ]]; then
        log "Mirror already exists: $local_path"
        exit 1
    fi

    log "Creating mirror of $REMOTE_HOST:$remote_repo_path..."

    # Clone as mirror
    git clone --mirror "$REMOTE_USER@$REMOTE_HOST:$remote_repo_path" "$local_path"

    log "Mirror created: $local_path"
    echo ""
    echo "To access this repo locally (read-only):"
    echo "  git clone $local_path"
}

cmd_list() {
    check_config
    echo "Local mirrors of $REMOTE_HOST:"
    echo ""
    local mirror_dir="$LOCAL_MIRROR_DIR/$REMOTE_HOST"
    if [[ -d "$mirror_dir" ]] && ls "$mirror_dir"/*.git 1>/dev/null 2>&1; then
        for repo in "$mirror_dir"/*.git; do
            local name=$(basename "$repo" .git)
            local last_fetch=$(git -C "$repo" log -1 --format="%ci" FETCH_HEAD 2>/dev/null || echo "never")
            printf "  %-30s (last sync: %s)\n" "$name" "$last_fetch"
        done
    else
        echo "  (no mirrors configured)"
    fi
    echo ""
}

cmd_list_remote() {
    check_config
    log "Listing repos on $REMOTE_HOST:$REMOTE_GIT_DIR..."
    echo ""
    ssh "$REMOTE_HOST" "ls -1 $REMOTE_GIT_DIR/*.git 2>/dev/null" || echo "(no repos found or directory doesn't exist)"
    echo ""
}

cmd_sync() {
    check_config
    if [[ -x "$SYNC_SCRIPT" ]]; then
        exec "$SYNC_SCRIPT"
    else
        echo "Sync script not found. Run '$0 setup' first."
        exit 1
    fi
}

cmd_init_repo() {
    local repo_name="${1:-}"

    if [[ -z "$repo_name" ]]; then
        echo "Usage: $0 init-repo <repo-name>"
        echo ""
        echo "Creates a new bare repository in $LOCAL_GIT_DIR"
        exit 1
    fi

    # Add .git suffix if not present
    [[ "$repo_name" != *.git ]] && repo_name="${repo_name}.git"

    local repo_path="$LOCAL_GIT_DIR/$repo_name"

    if [[ -d "$repo_path" ]]; then
        echo "Repository already exists: $repo_path"
        exit 1
    fi

    mkdir -p "$LOCAL_GIT_DIR"
    git init --bare "$repo_path"

    echo ""
    echo "Created bare repository: $repo_path"
    echo ""
    echo "To push an existing repo here:"
    echo "  git remote add origin $(hostname):$repo_path"
    echo "  git push -u origin main"
    echo ""
    echo "Tell your peer to mirror it with:"
    echo "  ./git-mirror-setup.sh add-mirror $repo_path"
}

cmd_status() {
    check_config
    echo "Git Mirror Status"
    echo "================="
    echo ""
    echo "Configuration:"
    echo "  Remote host:     $REMOTE_HOST"
    echo "  Remote user:     $REMOTE_USER"
    echo "  Remote git dir:  $REMOTE_GIT_DIR"
    echo "  Local git dir:   $LOCAL_GIT_DIR"
    echo "  Local mirrors:   $LOCAL_MIRROR_DIR/$REMOTE_HOST"
    echo "  Sync schedule:   $CRON_SCHEDULE"
    echo ""

    echo "Mattermost notifications:"
    if [[ -n "$MATTERMOST_WEBHOOK_URL" ]]; then
        echo "  Webhook:         configured"
        echo "  Channel:         ${MATTERMOST_CHANNEL:-"(webhook default)"}"
        echo "  Failures only:   $MATTERMOST_FAILURES_ONLY"
    else
        echo "  (not configured)"
    fi
    echo ""

    echo "SSH connectivity:"
    if ssh -o ConnectTimeout=5 "$REMOTE_HOST" "true" 2>/dev/null; then
        echo "  $REMOTE_HOST: OK"
    else
        echo "  $REMOTE_HOST: UNREACHABLE"
    fi
    echo ""

    echo "Cron job:"
    if crontab -l 2>/dev/null | grep -q "git-mirror-sync"; then
        crontab -l 2>/dev/null | grep "git-mirror-sync"
    else
        echo "  (not installed)"
    fi
    echo ""

    echo "Recent sync log:"
    if [[ -f "$LOG_FILE" ]]; then
        tail -5 "$LOG_FILE"
    else
        echo "  (no logs yet)"
    fi
}

cmd_test_notify() {
    if [[ -z "$MATTERMOST_WEBHOOK_URL" ]]; then
        echo "ERROR: MATTERMOST_WEBHOOK_URL is not configured."
        echo "Edit this script and set the webhook URL first."
        exit 1
    fi

    log "Sending test notification to Mattermost..."

    local payload
    payload=$(cat <<EOF
{
    "username": "Git Mirror",
    "icon_emoji": ":git:",
    "attachments": [{
        "color": "#0066cc",
        "title": ":test_tube: Git Mirror Test - $(hostname -s)",
        "text": "This is a test notification from git-mirror-setup.sh.\n\nIf you see this, notifications are working correctly!",
        "footer": "git-mirror-sync test | $(date '+%Y-%m-%d %H:%M:%S')"
    }]
}
EOF
)

    if [[ -n "$MATTERMOST_CHANNEL" ]]; then
        payload=$(echo "$payload" | jq --arg ch "$MATTERMOST_CHANNEL" '. + {channel: $ch}')
    fi

    if curl -s -X POST \
        -H "Content-Type: application/json" \
        -d "$payload" \
        "$MATTERMOST_WEBHOOK_URL"; then
        echo ""
        log "Test notification sent successfully!"
    else
        echo ""
        log "ERROR: Failed to send test notification"
        exit 1
    fi
}

cmd_help() {
    cat << EOF
Git Mirror Setup for Tailnet Peers

Usage: $0 <command> [args]

Commands:
  setup                 Initial setup (directories, cron, sync script)
  add-mirror <path>     Add a remote repo to mirror locally
  list                  List local mirrors
  list-remote           List repos available on remote machine
  sync                  Run sync now
  init-repo <name>      Create a new bare repo for sharing
  status                Show configuration and status
  test-notify           Send a test notification to Mattermost
  help                  Show this help

Workflow:
  1. Edit configuration at top of this script
  2. Run './git-mirror-setup.sh setup' on both machines
  3. Create repos: './git-mirror-setup.sh init-repo myproject'
  4. Mirror peer's repos: './git-mirror-setup.sh add-mirror /path/to/repo.git'

Mattermost Notifications:
  1. Create an incoming webhook in Mattermost:
     Integrations > Incoming Webhooks > Add Incoming Webhook
  2. Set MATTERMOST_WEBHOOK_URL in this script
  3. Test with: './git-mirror-setup.sh test-notify'
  4. Re-run setup to regenerate the sync script with notifications

EOF
}

# Main dispatch
case "${1:-help}" in
    setup)       cmd_setup ;;
    add-mirror)  cmd_add_mirror "${2:-}" ;;
    list)        cmd_list ;;
    list-remote) cmd_list_remote ;;
    sync)        cmd_sync ;;
    init-repo)   cmd_init_repo "${2:-}" ;;
    status)      cmd_status ;;
    test-notify) cmd_test_notify ;;
    help|--help|-h) cmd_help ;;
    *)
        echo "Unknown command: $1"
        cmd_help
        exit 1
        ;;
esac
